uni-meter {
  output = "uni-meter.output-devices.shelly-pro3em"
  input = "uni-meter.input-devices.generic-http"

  # Administrative endpoint of uni-meter. The emulated Shelly itself uses 80.
  http-server {
    port = 4711
  }

  output-devices {
    shelly-pro3em {
      # ECO-WORTHY broadcasts Shelly RPC requests to UDP port 8888.
      udp-port = 8888
      udp-interface = "0.0.0.0"
      forget-interval = 10s
    }
  }

  input-devices {
    generic-http {
      url = "http://127.0.0.1:18081/v1/json"
      polling-interval = 1s

      power-phase-mode = "tri-phase"
      energy-phase-mode = "mono-phase"

      channels = [{
        type = "json"
        channel = "power-l1"
        json-path = "$.powerPhase1"
      }, {
        type = "json"
        channel = "power-l2"
        json-path = "$.powerPhase2"
      }, {
        type = "json"
        channel = "power-l3"
        json-path = "$.powerPhase3"
      }, {
        type = "json"
        channel = "energy-consumption-total"
        json-path = "$.energyCounterIn"
        scale = 0.001
      }, {
        type = "json"
        channel = "energy-production-total"
        json-path = "$.energyCounterOut"
        scale = 0.001
      }]
    }
  }
}
